In [5]:
!pip install dash plotly pandas jupyter-dash -q

In [6]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

df = pd.read_csv(url)

df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Dataset Shape: (244, 7)

Columns:
['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
from dash import Dash, dcc, html
from dash.dependencies import Input, Output
import plotly.express as px

app = Dash(__name__)

app.layout = html.Div([
    html.H1("Restaurant Tips Dashboard", style={'textAlign': 'center'}),

    dcc.Dropdown(
        id='day_filter',
        options=[{'label': day, 'value': day} for day in df['day'].unique()],
        value='Sun',
        clearable=False
    ),

    dcc.Graph(id='bill_chart'),
    dcc.Graph(id='tip_chart')
])

@app.callback(
    [Output('bill_chart', 'figure'),
     Output('tip_chart', 'figure')],
    [Input('day_filter', 'value')]
)

def update_graphs(selected_day):
    filtered_df = df[df['day'] == selected_day]

    fig1 = px.bar(
        filtered_df,
        x='sex',
        y='total_bill',
        color='sex',
        title=f'Total Bill by Gender on {selected_day}'
    )

    fig2 = px.pie(
        filtered_df,
        names='smoker',
        title=f'Smoker Distribution on {selected_day}'
    )

    return fig1, fig2


app.run(jupyter_mode="inline", debug=False)

Dash is running on http://127.0.0.1:8050/

INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

 * Serving Flask app '__main__'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
INFO:werkzeug:Press CTRL+C to quit